### ISSUE TITLE
RuntimeError: LSL binary library file was not found

### ISSUE THREAD

**Issue by jsheunis** [LMBooth/pybci#19]
This is not a problem with the package, it's user error. I didn't install `lsl` separately before running `pybci --help` via command line. This was fixed by installing `lsl` on my Mac by running `brew install labstreaminglayer/tap/lsl`.

Just leaving this trace here for future reference in case other mac-users come across the same:

```
> pybci --help

Traceback (most recent call last):
  File "/Users/jsheunis/opt/miniconda3/envs/pybci/lib/python3.11/site-packages/pylsl/pylsl.py", line 1287, in <module>
    libpath = next(find_liblsl_libraries())
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
StopIteration

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/jsheunis/opt/miniconda3/envs/pybci/bin/pybci", line 5, in <module>
    from pybci.cli import main
  File "/Users/jsheunis/opt/miniconda3/envs/pybci/lib/python3.11/site-packages/pybci/__init__.py", line 1, in <module>
    from .pybci import PyBCI
  File "/Users/jsheunis/opt/miniconda3/envs/pybci/lib/python3.11/site-packages/pybci/pybci.py", line 1, in <module>
    from .Utils.LSLScanner import LSLScanner
  File "/Users/jsheunis/opt/miniconda3/envs/pybci/lib/python3.11/site-packages/pybci/Utils/LSLScanner.py", line 1, in <module>
    from pylsl import StreamInlet, resolve_stream
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jsheunis/opt/miniconda3/envs/pybci/lib/python3.11/site-packages/pylsl/__init__.py", line 2, in <module>
    from .pylsl import IRREGULAR_RATE, DEDUCED_TIMESTAMP, FOREVER, cf_float32,\
  File "/Users/jsheunis/opt/miniconda3/envs/pybci/lib/python3.11/site-packages/pylsl/pylsl.py", line 1296, in <module>
    raise RuntimeError(err_msg + __dload_msg)
RuntimeError: LSL binary library file was not found. Please make sure that the binary file can be found in the package lib folder
 (/Users/jsheunis/opt/miniconda3/envs/pybci/lib/python3.11/site-packages/pylsl/lib)
 or the system search path. Alternatively, specify the PYLSL_LIB environment variable.
 You can install the LSL library with conda: `conda install -c conda-forge liblsl`
or with homebrew: `brew install labstreaminglayer/tap/lsl`
or otherwise download it from the liblsl releases page assets: https://github.com/sccn/liblsl/releases
On modern MacOS (>= 10.15) it is further necessary to set the DYLD_LIBRARY_PATH environment variable. e.g. `>DYLD_LIBRARY_PATH=/opt/homebrew/lib python path/to/my_lsl_script.py`
```

**Comment by jsheunis** [comment]
FTR, you can close this issue (possibly with a tag e.g. `mac` or something)
